export const CHANGE_DIALOG_OPEN = 'DIALOG/CHANGE_DIALOG_OPEN'
export const CHANGE_DIALOG_TYPE = 'DIALOG/CHANGE_DIALOG_TYPE'

export const CHANGE_USER_USERNAME = 'USER/CHANGE_USER_USERNAME'
export const CHANGE_USER_LOGIN = 'USER/CHANGE_USER_LOGIN'
export const CHANGE_USER_PHONE = 'USER/CHANGE_USER_PHONE'